### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by carlagesa** [PlotiHub/plotihub#18]
Write a proper **README.md** file for the project.
The readme file should also include this ERD file [link](https://dbdiagram.io/d/634abab5f0018a1c5f0d9b20)
For more information read this [article](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/)
Easiest way to create a [readme](https://readme.so/)

**Comment by PhamNguyen01** [comment]
Hello carlagesa can I help you with this PR.
Let me know what Plotihub project is used for?
I will provide a PR with above requirements do you need some more?

**Comment by carlagesa** [comment]
Hello PhamNguyen01, PlotiHub is an open source property management system that aims to change how property management is done in Kenya. PlotiHub ensures user data is safe and accounted for hence eliminating any possible human errors.

**Comment by PhamNguyen01** [comment]
# PlotiHub

PlotiHub is an open source property management system that aims to change how property management is done in Kenya. PlotiHub ensures user data is safe and accounted for hence eliminating any possible human errors.

[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](https://github.com/PlotiHub/plotihub)

## Authors

- [@carlagesa](https://github.com/carlagesa)


## Tech Stack

[![Readme Card](https://github-readme-stats.vercel.app/api/pin/?username=PlotiHub&repo=plotihub)](https://github.com/PlotiHub/plotihub)


## License

[![License](https://img.shields.io/badge/LICENSE-CC_BY_4.0-00a2ff?&style=flat-square)](https://creativecommons.org/licenses/by/4.0/)

**Comment by PhamNguyen01** [comment]
> Hello PhamNguyen01, PlotiHub is an open source property management system that aims to change how property management is done in Kenya. PlotiHub ensures user data is safe and accounted for hence eliminating any possible human errors.

Could you please give this issues to me and can you add me as the assignee? The above is a demo of the readme file that I designed
If you need any more information, feel free to reply to me (such as License, features, sponsors,...).

**Comment by carlagesa** [comment]
Noted 
Add ~

- The project is built on React, Material UI, Ruby on Rails & PostgreSQL 
- Also add a link to this ERD file https://dbdiagram.io/d/634abab5f0018a1c5f0d9b20
- State that the design file link will be available soon
- How to get started with the project`git clone git@github.com:PlotiHub/plotihub.git` & `cd plotihub` & `npm install --prefix client` & `npm start --prefix client` & also start rails server by running `rails s`
- Will be sending a link to the API documentation by the end of the day.

**Comment by PhamNguyen01** [comment]
Sorry, I have a problem when I upload the readme.md file  
![image](https://user-images.githubusercontent.com/113649670/201729219-40728897-42cd-4649-92d5-eae773353117.png)
Look forward to the help.
Thank you.

**Comment by carlagesa** [comment]
See https://github.com/PlotiHub/plotihub/blob/main/CONTRIBUTING.md

**Comment by PhamNguyen01** [comment]
I finished the Readme.md file
Looking forward to your feedbacks

**Comment by carlagesa** [comment]
Wow, that was awesome. Thank you @PhamNguyen01 for your contribution.
